### ISSUE TITLE
Filter logic

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-client-html#176]
Hi!
Something goes wrong with the logic of the filter.
This product is available in 2 colors (Beige and Blue):
![image](https://user-images.githubusercontent.com/61547701/161135588-6530a1cc-63ce-4b69-b45d-5535147da09c.png)
If I filter to Beige, the Blue color in the filter remains active.
![image](https://user-images.githubusercontent.com/61547701/161134761-50bfac9a-169d-47d1-92ef-a6e3c265de99.png)
I don't understand the logic in this.
Why does the color Blue remain active?
If I click on the Blue after the Beige, I get zero hits.
If I click on the Black after the Beige, I get zero hits.
I understand these are two separate products, and the filter uses an AND connection, but that's misleading, isn't it?

**Comment by aimeos** [comment]
Showing "Blue" as available is correct because for the selection product, "Beige" and "Blue" variants are available but there shouldn't be zero products when clicking on "Blue" too.

The alternative would be to apply an OR condition so it's "Beige" or "Blue" using "color" in this setting: 
https://aimeos.org/docs/2021.x/config/client-html/catalog-filter/#types-option

**Comment by aimeos** [comment]
Filtering for multiple attributes of the same type has been fixed now. The fix is available in dev-master, 2022.04.x-dev and 2021.10.x-dev and will be part of the next release.
