### ISSUE TITLE
Canceling on PayPal

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/ai-client-html#18]
If someone cancels a payment at PayPal he will be returned to confirm page with two buttons "change payment" and "try again". The third option "continue shopping" would be nice. And perhaps "cancel purchase", but this is not so important I think.

Yesterday we had the case that someone canceled on PayPal and 50 minutes later we have received a second purchase with on additional product in the order payed and confirmed at / by PayPal. First order is on payment pending and has to be canceled by hand.

**Comment by aimeos** [comment]
I think, that's an edge case that someone cancels the payment because he forgot to order something. He always has the possibility to return to the shopping pages via the menu or a link in the page header. His basket content is still there in this case and that's the important thing.

When clicking the "Cancel" link at the PayPal page, the order status should be set to canceled automatically. We will check this.

**Comment by aimeos** [comment]
If a user clicks on "Cancel" at the PayPal page, the Aimeos payment status stays to "unfinished", which is OK because there's no real response from PayPal in this case. Your customer must have been payed in one or the other way.

BTW: Your shop does still show the "coming soon" page. Is this correct?

**Comment by gilbertsoft** [comment]
Should not, page was renamed before 2 days. Caching issue I think?

The behaviour of PayPal canceling is correct. I only think it's easier to understand for customers if they have a button "continue shopping". But you're absolutly right, it's possible to continue shopping and adding removing products from the basket and doing the checkout again, that works fine!

**Comment by aimeos** [comment]
Yes, it was a caching issue. Others who visited the page before might also have this problem.

You should add a HTTPS certificate as soon as possible to protect your customers. LetsEncrypt certificates for example are for free.

**Comment by gilbertsoft** [comment]
Thanks for the hint, had no time to request for a cert. I'm using ISPConfig, they have LetsEncrypt implemented as I know.

**Comment by gilbertsoft** [comment]
The caching issue is a bad thing, but can't change anymore. The static intro page was made by another implementor and I just copied it without checking for an expires tag and there was nothing defined. Requests to /index.html are handled by TYPO3 since deleting the old file, but if the browser doesn't make a new request, I can't do anything

**Comment by aimeos** [comment]
Your web site isn't reachable at the moment because of a wrong redirect to https://.zwergenfabrik.ch/ (dot at the beginning)

**Comment by gilbertsoft** [comment]
Should be solved, had some troubles installing the SSL cert. Now online with SSL only :-D

**Comment by aimeos** [comment]
After clearing the browser cache, everything seems to be fine now :-)
