### ISSUE TITLE
coupon code cannot be deleted if all products are removed

### ISSUE THREAD

**Issue by ulgerman** [aimeos/ai-client-html#36]
Hey,

I'm testing the shop module right now.
I've added some products to the cart and applied a coupon code
The amount was correct.
Then I deleted all the products , but the coupon code stayed active (the total amount was negative -125)

even when I click on the shopping cart icon ( top right of site) , I see the garbage icon next to the coupon code , the code cannot be deleted

Thanx for your time
johan

**Comment by aimeos** [comment]
The demo site doesn't show this behavior: http://laravel.demo.aimeos.org/default/en/EUR/list
Please add more details about the coupon you are using and its configuration

**Comment by ulgerman** [comment]
I see the same behavior on the demo site

1) http://laravel.demo.aimeos.org/default/en/EUR/detail/10019/Demo_article/0
I added 1 item
2) I entered coupon code 'fixed'
3) the total amount = -20euro
4) the I remove the article
5) total amount = -125 euro
6) I go back to list page :http://laravel.demo.aimeos.org/default/en/EUR/list
7) I open top right cart and try to delete coupon code . but it does not work

thanx for your time 
johan

**Comment by aimeos** [comment]
Thank you for the helpful bug report. These are two issues:

1.) For coupon injected products there must be no link to delete the product in the small basket. This is fixed in the new ai-client-html version (use composer update)

2.) To prevent negative values, you should add the `BasketValues` decorator to the `FixedRebate` provider and configure a minimum basket value with the same amount as rebate amount:
![admin-coupon-basketmin](https://user-images.githubusercontent.com/8647429/29437202-9188a7a4-83af-11e7-877a-dda6cd18808d.png)

**Comment by ulgerman** [comment]
once again thanx for the quick reply !
