### ISSUE TITLE
Search only searches in default category

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-client-html#57]
When a default category is set (e.g. via `client/html/catalog/lists/catid-default`), the search function only lists search results from this default category. This might be counterintuitive, especially because the `suggest` function lists products from all categories.

Is this desired behaviour?

See https://github.com/aimeos/ai-client-html/blob/c1f1023fb39f7a3891709a48bea50e428e832164/client/html/src/Client/Html/Catalog/Base.php#L233-L255 for the cause of this issue.

**Comment by aimeos** [comment]
Might be worth discussing. Suggestion: We can add `$text != ''` to the if-condition

**Comment by nvindice** [comment]
That would have been my approach, too. 
(I guess you wanted to suggest `&& $text == ''` in the if clause - if there IS a search phrase in `text` then there should be no default category filter, right...?!)

**Comment by aimeos** [comment]
Yes, right :-)
Can you make a PR for the change? In current master branch the code looks a bit different

**Comment by nvindice** [comment]
Made a PR for 2018.10 first, see #58 

Frankly, I am not familiar with the new 2019 build. But I will create a PR for the master branch, too, so you can have a look at my suggestion.

**Comment by meisterkaiser** [comment]
(msg moved from PR - better discuss it here)
the suggested change effectively disables limitation of results to a default category at all when using the keyword search. Is this really the intended behaviour?

After the change my setup is broken:
a site with two independent sets of articles grouped by two main category (and their unique subcategories). After the change I get results from the other main category when using the keyword search, which is absolutely undesirable.

In my optinion the new behavior should be configurable, because it can break existing behaviour.
(That said: not setting a default category should produce the same results, so the intention of the change is still unclear to me after all ...)

**Comment by nvindice** [comment]
Well, the configuration setting `client/html/catalog/lists/catid-default` does not seem to be related to the search function at all (see comment/manual). So IMHO the old behaviour was not intended. Most shops use a keyword search function page-wide if no category is set.

To your specific case: Why don't you just pass a category with the search form? I don't see how a default category would solve your problem with 2 main categories...

**Comment by meisterkaiser** [comment]
Exactly, if no category is set.
In my case a default category is set in the filter plugin, showing products only from that category (and its subcategories) in the results. If you take a look at the code again (reduced to relevant parts & comments removed):

```php
$text = ( isset( $params['f_search'] ) ? (string) $params['f_search'] : '' );

if( $catid == '' && $catfilter === true && $text == '')
{
    $catid = $config->get( 'client/html/catalog/lists/catid-default', '' );
}
```
$text is filled with the keyword. Due to the changed condition in this case (and this case only) the configured default category will **not** be used. As far as I can see there was no relation between search and configured category before, but the changed condition establishes one.
Or am I missing something?

Your suggestion: 
if I set a default category in the plugin, why introduce extra steps to make it work as expected again? Doesn't make much sense to me :)

**Comment by aimeos** [comment]
@nvindice Can you explain why you've set a default category and want to use the full text search over all products? Is it because the suggest plugin searches over all products?

**Comment by nvindice** [comment]
@aimeos Nope, very simple: I've set a default category, so that I can select which products are listed at the start page (no category set). But as I said, every shop I know uses keyword search over all categories, when no category is set _explicitely_ (by the user!).

@meisterkaiser I understand your use case, but I don't think changing the _default_ category each time the user clicks onto something is the intended usage of this setting :-) This is why it is called _default_, right...? Your use case sounds like the perfect example for setting a regular (base) category. Also, there is a setting to traverse through X levels of sub-categories, I'm sure @aimeos knows the name of it.

As I already said before: Before this PR, there in fact _was_ a relation between search and _default category_, which should not be there IMHO. Making this configurable is possible, but not useful (other than helping people who used this "bug" before, of course). I am very convinced that the current way is expected behaviour by most users and should be the default way.

**Comment by aimeos** [comment]
@nvindice You are right, what you describe is what most users expect. The problem is how you do it. We would suggest to add a new search page without default category set and point the filter plugin to that page instead of your home page with the catalog list component and the default category setting.

**Comment by nvindice** [comment]
@aimeos I can do that, no problem. However, as we strive to improve the product, I don't see why we should use a behaviour as default which most users _don't_ expect.

I'm pretty sure some developers will set up a new shop, define a default category and not even notice that the keyword search function hides many products because it only seaches the default category.

**Comment by aimeos** [comment]
@nvindice The current problem is that there are use cases which require that behavior and we made them impossible with the change. To enable both, use a default category if set and search for all products in a global search, we need to use different ways to achieve that

**Comment by nvindice** [comment]
@aimeos I can't see any use case which has been made impossible by the new (intuitive) behaviour. The use case @meisterkaiser mentioned would be structurally better if he set a category with his plugin instead of overwriting the default category, IMHO. That's what categories are for. Or am I missing something?

**Comment by aimeos** [comment]
The category selection in the plugin sets the `catid-default` option IIRC so it wouldn't help

**Comment by nvindice** [comment]
Yes, but why? Better change it to just set the category. This would by way cleaner IMHO. Let's wait for @meisterkaisers view on things.

**Comment by nvindice** [comment]
I'm kind of disappointed that you just reverted back to the broken (at least counterintuitive) version. While I do understand this decision for 2018.x, I think at least 2019.x should not continue doing it this way by default. These are my 2 cents - however, your project, your decision.

**Comment by aimeos** [comment]
For 2018.10 it's a breaking change in a minor LTS version which is absolutely undesired if users already rely on it. For 2019.x things can be different but we also want to get feedback from @meisterkaiser first if there's a better way to do what he tries to achieve.

**Comment by meisterkaiser** [comment]
Sorry for the late reply!
From my point of view it's highly confusing to set a default category in the filter plugin - only to find that it is not respected in certain cases.

To make this more clear: I don't see @nvindice's case as the expected behaviour from a developer's perspective, but his case is still valid for website users.
So l think it should not be the default, but a configurable option instead, something like "Override default category for keyword searches".

That would allow an easy setup for @nvindice 's case, while at the same time giving developers back control and an understanding over what's actually happening.

**Comment by aimeos** [comment]
We are hesitating a bit to add another configuration option for something that is better done with two list views (one with default category and one without). From the developer perspective it should work as expected when setting a default category without any "if"s. Perhaps it's better to add more text to the configuration to point developers to the fact that this limits full text search as well.

**Comment by nvindice** [comment]
I don't think a configuration option is the best way, either.

But: I'm still not convinced that this is intuitive from the developer's view. And I'm not convinced that there is a good reason to use the default category for fulltext search in any way. My bet ist: 99% of all developers set the default category once, expecting it to limit the list on the start page. They will not expect this parameter to limit the keyword search.

In the rare case a developer wants to limit keyword search over categories, he has to use `client/html/catalog/filter/tree/force-search` and add a category to that search. The documentation there states:
> Normally, a full text search finds all products that match the entered string regardless of the category the user is currently in. This is also the standard behavior of other shops. 
This is absolutely true and should be the same for the default category IMHO. I don't think it makes much sense to normally NOT use the category as default behaviour but use it here in this single case (no category given). This seems to be ultimately counterintuitive for me.

AT LEAST the default category should ONLY be used if `client/html/catalog/filter/tree/force-search = true`.

**Comment by meisterkaiser** [comment]
So the current suggestion is:
A restriction of search results to certain categories can be configured per plugin, yet an exception to that is or should be hard-coded (!), then developers should use a separete configuration option to restore the restriction again.
Sorry, I don't see any logic or "intuitive" behaviour in that.
A clean solution should work the opposite way: an extra option should trigger the exception to the rule (instead of restoring it). The exception could be set as default for all I care - I don't want to discuss opinions on standard behaviour of shops, only the cleanest possible way to achieve several valid use cases.

I looked into the solution suggested by @nvindice, as far as I can see it simply does not work without further actions. ```client/html/catalog/filter/tree/force-search``` is used once, in tree-body-standard.php. If set, a hidden field is inserted into the form and filled with a category id taken from form parameters - no default-category set globally or default-category from the plugin is used.
@aimeos : Missing piece of code or is the documentation wrong / misleading? What did I fail to see? 

I tried to solve it in an overridden template, but didn't succeed in accessing the default-category set in the plugin ( maybe I missed the proper way - open for suggestions ).

**Comment by aimeos** [comment]
@meisterkaiser The behavior of `client/html/catalog/filter/tree/force-search` in the tree component is as you say and it wasn't intended to interfere with the `catid-default` setting of the list component. So both are independent and I don't know if it's a good thing to use it for both

**Comment by nvindice** [comment]
Maybe it would be the cleanest solution if the `client/html/catalog/filter/tree/force-search` setting was restructured and then used for both (adding a hidden field in the template and restricting the search to the default category in `Catalog\Base`?

@meisterkaiser I see it the other way around: The keyword search always searches in all categories (with default settings), EXCEPT for the single exception that the user is on the start page (no category set -> default category). This is a very confusing behaviour to me.

Maybe I still don't understand exactly what you are trying to achive. You use a plugin to set a default category dynamically. Do you want to limit all searches only to this category? IMHO, this is exactly what _regular_ categories are for? Why do you set the _default_ category instead?

**Comment by meisterkaiser** [comment]
@nvindice :
There's no weird stuff going on, I am simply using what the typo3 Catalog list plugin offers: "Default category if no parameter is available". Plugins are page based, and I am using this setting to configure different behaviour on two independent pages living in different spots within the website:
* page A: list books (all products that are members of "books" category or its subcategories)
* page B: list editions of a magazine (all products that are members of the "magazine" category or its subcategories)
On both pages a filter plugin is also present with specific filter & sorting settings and - tadaa - keyword search. Each page is supposed to list products from their configured category (& subcategories) **only**. No mingling allowed.

Setting says: "Default category if no parameter is available" and that is exactly what I am expecting: show results only from the configured category. In all cases. Except (and that's the only exception): another category is given in form parameters. 
This is what the config option suggests, this is what I expect. It's that simple :)

As said - I totally see your use case too. Your suggestion using ```client/html/catalog/filter/tree/force-search``` unfortunately does not work though and according to @aimeos is not even supposed to be a solution...

@aimeos: Perfectly willing to use another (existing?) config option. 
I think everything has been said more than once already about what should be default behaviour, and why - I don't see much sense in discussing this further. Probably too biased by personal opinion anyway...
Seems you have to decide about the way you prefer to enable both scenarios ... ?

**Comment by nvindice** [comment]
@meisterkaiser Thank you for the explanation, I really did miss the point! I thought you were talking about some kind of self-written aimeos plugin which changes the default category on different calls. This seemed to be very... unusual to me :-)

So, let's summarize. Current situation:

- a set default category limits the (default) catalog list, if no category is set. This affects probably many shop start pages.
- a set default category limits the keyword search in 2018.10 (a useful feature for some cases)
- keyword search is not limited by any category _set_ **but** the _default category_, which might be confusing for developers (at least in my opinion this is a bug)

As we have the chance with 2019.x to define a new default behaviour, the main question is IMHO: **In which cases should the keyword search be limited (if any)?**

Possible concepts:
- keyword search is always limited to the current category
- keyword search is always shop-wide (like in most shops)
- keyword search _can_ be limited to a list of specified categories (= new config option)
- keyword search is always shop-wide unless a default category is set and no category is defined (current solution, but IMHO not good)

@meisterkaiser Feel free to add another possible solution, if I forgot one.

@aimeos Feel free to simply decide. I'm not going to use 2019.x anywhere soon, and I found a solution for all of my use cases. I have no personal interest in this discussion anymore but would like to improve the product. However, as my resources are limited, I'm not going to follow this discussion anymore.

**Comment by aimeos** [comment]
There are valid arguments for both behaviors. Due to the fact that nobody else complained about the current behavior since the last six month, we will leave it as is.
